In [48]:
import pyprind
import pandas as pd
import os
import sys
import numpy as np
sys.getdefaultencoding()

'utf-8'

In [57]:
pbar = pyprind.ProgBar(50000)
label = {'pos':1,'neg':0}
df = pd.DataFrame()
for s in ('test','train'):
    for l in ('pos','neg'):
        path = '/Users/MLUSER/Documents/GitHub/ML-PACKT/aclImdb/%s/%s'%(s,l)
        for file in os.listdir(path):
            with open(os.path.join(path,file),'r', encoding='utf-8') as infile:
                txt = infile.read()
            df = df.append([[txt,label[l]]],ignore_index=True)
            pbar.update()


0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:03:48


In [66]:
df.columns = ['review','sentiment']

In [67]:
np.random.seed(0)
df = df.reindex(np.random.permutation(df.index))
df.to_csv('/Users/MLUSER/Documents/GitHub/ML-PACKT/aclImdb/moive_data.csv',encoding='utf-8',index=False)

In [68]:
df = pd.read_csv('/Users/MLUSER/Documents/GitHub/ML-PACKT/aclImdb/moive_data.csv')

df.head()

review  sentiment
0  I finally managed to sit through a whole episo...          0
1  Just what the world needed-another superficial...          0
2  I have to say despite it's reviews Angels in t...          1
3  Only the chosen ones will appreciate the quali...          1
4  Anne (Natalie Portman) tells us about how much...          1

In [81]:
from sklearn.feature_extraction.text import CountVectorizer
#
count = CountVectorizer()
docs = np.array(['the sun is shining',
                'the weather is sweet',
                'the sun is shining and the weather is sweet'])
bag = count.fit_transform(docs)
print (count.vocabulary_)
print (bag.toarray())

{'sun': 3, 'sweet': 4, 'and': 0, 'the': 5, 'is': 1, 'shining': 2, 'weather': 6}
[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 2 1]]
